name: Focalors-Trial-System
version: '${project.version}'
description: Focalors Trial System (The God of Justice)
author: Shizoukia, FallenCrystal
main: net.miaomoe.shizoukia.focalors.Focalors
commands:
  focalors:
    description: focalors main help
    aliases: [fts]